# Generated by Django 4.2.7 on 2026-01-31 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "private_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "recipient", "-created_at"],
                        name="private_mes_sender__28ed95_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="private_mes_recipie_ee7a38_idx",
                    ),
                ],
            },
        ),
    ]
