# Generated by Django 4.2.7 on 2026-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_privatemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("mention", "Mentioned"),
                    ("reply", "Reply"),
                    ("reaction", "Reaction"),
                    ("decision", "Decision"),
                    ("reminder", "Reminder"),
                    ("badge", "Badge Earned"),
                    ("automation", "Automation"),
                    ("message", "Message"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
    ]
