# Generated by Codex on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("mention", "Mentioned"),
                    ("reply", "Reply"),
                    ("reaction", "Reaction"),
                    ("decision", "Decision"),
                    ("task", "Task"),
                    ("goal", "Goal"),
                    ("meeting", "Meeting"),
                    ("issue_assigned", "Issue Assigned"),
                    ("reminder", "Reminder"),
                    ("badge", "Badge Earned"),
                    ("automation", "Automation"),
                    ("message", "Message"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
    ]

