# Generated by Django 4.2.7 on 2026-05-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_emailcampaign_emailcampaignrecipient'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='email_campa_organiz_b85cee_idx',
            old_name='email_campa_organiz_91b61c_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaignrecipient',
            new_name='email_campa_campaig_be2e04_idx',
            old_name='email_campa_campaig_3eb421_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaignrecipient',
            new_name='email_campa_email_35958f_idx',
            old_name='email_campa_email_c724f9_idx',
        ),
    ]
