# Generated by Django 5.2.14 on 2026-08-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_email_campa_organiz_91b61c_idx_email_campa_organiz_b85cee_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mentioned'), ('reply', 'Reply'), ('reaction', 'Reaction'), ('decision', 'Decision'), ('task', 'Task'), ('goal', 'Goal'), ('meeting', 'Meeting'), ('issue_assigned', 'Issue Assigned'), ('reminder', 'Reminder'), ('badge', 'Badge Earned'), ('automation', 'Automation'), ('capture', 'Captured'), ('message', 'Message'), ('system', 'System')], max_length=20),
        ),
    ]
