# Generated by Django 4.2.7 on 2025-12-26 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Impact"),
                            ("medium", "Medium Impact"),
                            ("high", "High Impact"),
                            ("critical", "Critical Impact"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("impact_assessment", models.TextField(blank=True)),
                ("alternatives_considered", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "implementation_deadline",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("extracted_by_ai", models.BooleanField(default=False)),
                ("ai_confidence_score", models.FloatField(blank=True, null=True)),
                ("outcome_notes", models.TextField(blank=True)),
                ("success_metrics", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "decisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DecisionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("description", models.TextField(blank=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "decision_tags",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="DecisionTagging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decisions.decision",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decisions.decisiontag",
                    ),
                ),
            ],
            options={
                "db_table": "decision_tagging",
            },
        ),
    ]
