# Generated by Django 4.2.7 on 2025-12-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0002_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("decisions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisiontagging",
            name="tagged_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="decisiontag",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="decision_maker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="stakeholders",
            field=models.ManyToManyField(
                blank=True,
                related_name="decisions_involved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="decisions",
                through="decisions.DecisionTagging",
                to="decisions.decisiontag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="decisiontagging",
            unique_together={("decision", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="decisiontag",
            unique_together={("name", "organization")},
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="decisions_organiz_b2fa74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "decision_maker", "-created_at"],
                name="decisions_organiz_a22834_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "impact_level", "-created_at"],
                name="decisions_organiz_fba641_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["decided_at"], name="decisions_decided_828ed1_idx"
            ),
        ),
    ]
