# Generated by Django 4.2.7 on 2025-12-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_mentions_tags"),
        ("decisions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="conversations.conversation",
            ),
        ),
    ]
