# Generated by Django 4.2.7 on 2025-12-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_conversation_why_this_matters_and_more"),
        ("decisions", "0003_alter_decision_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="reminder_days",
            field=models.IntegerField(
                default=30, help_text="Days after approval to remind"
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="reminder_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="conversations.conversation",
            ),
        ),
    ]
