# Generated by Django 4.2.7 on 2025-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decisions", "0004_decision_last_reminded_at_decision_reminder_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="confidence_level",
            field=models.IntegerField(
                blank=True,
                help_text="1-10: How confident are you this will work?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="confidence_votes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of {user_id, vote, timestamp}"
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="context_reason",
            field=models.TextField(
                blank=True, help_text="Why are we even talking about this?"
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="if_this_fails",
            field=models.TextField(
                blank=True, help_text="What happens if this doesn't work?"
            ),
        ),
    ]
