# Generated by Django 4.2.7 on 2025-12-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "decisions",
            "0005_decision_confidence_level_decision_confidence_votes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="code_links",
            field=models.JSONField(
                blank=True, default=list, help_text="Links to PRs, commits, docs"
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="plain_language_summary",
            field=models.TextField(blank=True, help_text="Non-technical explanation"),
        ),
        migrations.AddField(
            model_name="decision",
            name="tradeoffs",
            field=models.TextField(blank=True, help_text="What are the tradeoffs?"),
        ),
    ]
