# Generated by Django 4.2.7 on 2025-12-30 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "decisions",
            "0006_decision_code_links_decision_plain_language_summary_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="impact_review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="is_locked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="decision",
            name="lessons_learned",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="lock_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="review_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="review_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="was_successful",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DecisionLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("override_reason", models.TextField()),
                ("overridden_at", models.DateTimeField(auto_now_add=True)),
                ("previous_value", models.JSONField()),
                ("new_value", models.JSONField()),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock_overrides",
                        to="decisions.decision",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decision_lock_overrides",
                "ordering": ["-overridden_at"],
            },
        ),
        migrations.CreateModel(
            name="SimilarDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("similarity_reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_to",
                        to="decisions.decision",
                    ),
                ),
                (
                    "similar_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_from",
                        to="decisions.decision",
                    ),
                ),
            ],
            options={
                "db_table": "similar_decisions",
                "ordering": ["-similarity_score"],
                "unique_together": {("decision", "similar_decision")},
            },
        ),
    ]
