# Generated by Django 4.2.7 on 2025-12-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0002_sprintupdate"),
        ("decisions", "0007_decision_impact_review_notes_decision_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisions",
                to="agile.sprint",
            ),
        ),
    ]
