# Generated by Django 4.2.7 on 2026-01-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decisions", "0009_proposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="code_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="decision",
            name="confidence_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="confidence_votes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="decision",
            name="context_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="if_this_fails",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="plain_language_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="reminder_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="decision",
            name="tradeoffs",
            field=models.TextField(blank=True),
        ),
    ]
