# Generated by Django 4.2.7 on 2026-01-31 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_searchanalytics_savedsearch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("decisions", "0010_alter_decision_code_links_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rationale", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approvals", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_proposal",
                        to="decisions.decision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_approvers",
                    models.ManyToManyField(
                        related_name="decisions_to_approve", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "decision_proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_records",
                        to="decisions.decisionproposal",
                    ),
                ),
            ],
            options={
                "db_table": "proposal_approvals",
                "unique_together": {("proposal", "approver")},
            },
        ),
        migrations.CreateModel(
            name="DecisionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Decision"),
                            ("process", "Process Decision"),
                            ("hiring", "Hiring Decision"),
                            ("budget", "Budget Decision"),
                            ("strategy", "Strategy Decision"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("fields", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "decision_templates",
                "ordering": ["template_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "template_type"],
                        name="decision_te_organiz_a1a681_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="decisionproposal",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="decision_pr_organiz_5beb6f_idx",
            ),
        ),
    ]
