# Generated by Django 4.2.7 on 2026-01-31 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_searchanalytics_savedsearch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "decisions",
            "0011_decisionproposal_proposalapproval_decisiontemplate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performance"),
                            ("revenue", "Revenue"),
                            ("cost", "Cost"),
                            ("efficiency", "Efficiency"),
                            ("quality", "Quality"),
                            ("adoption", "Adoption"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("baseline_value", models.FloatField()),
                ("baseline_date", models.DateField()),
                ("current_value", models.FloatField(blank=True, null=True)),
                ("current_date", models.DateField(blank=True, null=True)),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="decisions.decision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "decision_metrics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsensusSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_votes", models.IntegerField()),
                ("approve_count", models.IntegerField()),
                ("reject_count", models.IntegerField()),
                ("abstain_count", models.IntegerField()),
                ("approval_percentage", models.FloatField()),
                ("avg_confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_snapshots",
                        to="decisions.decision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "consensus_snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("recorded_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="decisions.decisionmetric",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metric_data_points",
                "ordering": ["recorded_date"],
                "unique_together": {("metric", "recorded_date")},
            },
        ),
        migrations.CreateModel(
            name="DecisionVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("abstain", "Abstain"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(default=5, help_text="1-10 confidence level"),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="decisions.decision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decision_votes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "decision", "-created_at"],
                        name="decision_vo_organiz_363ca9_idx",
                    )
                ],
                "unique_together": {("decision", "voter")},
            },
        ),
        migrations.AddIndex(
            model_name="decisionmetric",
            index=models.Index(
                fields=["organization", "decision", "-created_at"],
                name="decision_me_organiz_4132ee_idx",
            ),
        ),
    ]
