# Generated by Django 5.2.14 on 2026-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0014_decision_informed_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='decisionoutcomecheck',
            new_name='decision_ou_organiz_e83663_idx',
            old_name='dec_chk_org_band_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionoutcomecheck',
            new_name='decision_ou_predict_df49a6_idx',
            old_name='dec_chk_pred_obs_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionprediction',
            new_name='decision_pr_organiz_ae959d_idx',
            old_name='dec_pred_org_check_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionprediction',
            new_name='decision_pr_decisio_6fdc4d_idx',
            old_name='dec_pred_dec_check_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionretrospective',
            new_name='decision_re_organiz_c4fb30_idx',
            old_name='dec_retro_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionretrospective',
            new_name='decision_re_decisio_51ff6e_idx',
            old_name='dec_retro_dec_created_idx',
        ),
        migrations.RenameIndex(
            model_name='decisiontwinrun',
            new_name='decision_tw_organiz_0464ba_idx',
            old_name='dec_twin_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='decisiontwinrun',
            new_name='decision_tw_decisio_564489_idx',
            old_name='dec_twin_dec_created_idx',
        ),
        migrations.RenameIndex(
            model_name='decisiontwinrun',
            new_name='decision_tw_organiz_dffed9_idx',
            old_name='dec_twin_org_status_idx',
        ),
        migrations.AlterField(
            model_name='decisionoutcomecheck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='decisionprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='decisionretrospective',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='decisiontwinrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
