# Generated by Django 5.2.14 on 2026-06-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_conversationthread_conversationhistory'),
        ('decisions', '0015_rename_dec_chk_org_band_idx_decision_ou_organiz_e83663_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='conversations.conversation'),
        ),
    ]
