# Generated by Django 4.2.7 on 2026-08-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Let a decision say which project it is about.

    A workspace holds several projects, and the record did not know which one
    anything belonged to — nine decisions in one workspace spanning two
    unrelated projects, pooled together. Nullable on purpose: not every
    decision is about code, and requiring a project would make people invent
    one.
    """

    dependencies = [
        ('agile', '0028_releases_timestamptz'),
        ('decisions', '0016_align_conversation_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='agile.project'),
        ),
    ]
