# Generated by Django 4.2.7 on 2025-12-30 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0008_user_first_conversation_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversations", "0014_conversation_draft_saved_at_conversation_is_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("goal", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("completed_count", models.IntegerField(default=0)),
                ("blocked_count", models.IntegerField(default=0)),
                ("decisions_made", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sprints",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Retrospective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("what_went_well", models.JSONField(default=list)),
                ("what_needs_improvement", models.JSONField(default=list)),
                ("action_items", models.JSONField(default=list)),
                ("recurring_issues", models.JSONField(default=list)),
                ("positive_trends", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrospectives",
                        to="agile.sprint",
                    ),
                ),
            ],
            options={
                "db_table": "retrospectives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Blocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "blocker_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("dependency", "Dependency"),
                            ("decision", "Decision Needed"),
                            ("resource", "Resource"),
                            ("external", "External"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("ticket_url", models.URLField(blank=True)),
                ("ticket_id", models.CharField(blank=True, max_length=50)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockers_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockers_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockers",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockers",
                        to="agile.sprint",
                    ),
                ),
            ],
            options={
                "db_table": "blockers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["organization", "-start_date"],
                name="sprints_organiz_95b956_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blocker",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="blockers_organiz_f53ec3_idx",
            ),
        ),
    ]
