# Generated by Django 4.2.7 on 2025-12-30 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_user_first_conversation_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sprint_update", "Sprint Update"),
                            ("blocker", "Blocker"),
                            ("decision_impact", "Decision Impact"),
                        ],
                        default="sprint_update",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("ai_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="agile.sprint",
                    ),
                ),
            ],
            options={
                "db_table": "sprint_updates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "sprint", "-created_at"],
                        name="sprint_upda_organiz_f7684f_idx",
                    )
                ],
            },
        ),
    ]
