# Generated by Django 4.2.7 on 2026-01-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0003_board_column_issue_project_issuelabel_issuecomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprints",
                to="agile.project",
            ),
        ),
    ]
