# Generated by Django 4.2.7 on 2026-01-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0004_sprint_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["project", "-start_date"], name="sprints_project_c93ab7_idx"
            ),
        ),
    ]
