# Generated by Django 4.2.7 on 2026-01-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0009_automationtemplate_dashboard_integration_and_more"),
        ("agile", "0005_sprint_status_sprint_sprints_project_c93ab7_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="branch_name",
            field=models.CharField(
                blank=True, help_text="Git branch name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="ci_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                help_text="CI/CD pipeline status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="ci_url",
            field=models.URLField(blank=True, help_text="CI/CD pipeline URL"),
        ),
        migrations.AddField(
            model_name="issue",
            name="code_review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes Requested"),
                    ("merged", "Merged"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="commit_hash",
            field=models.CharField(
                blank=True, help_text="Git commit hash", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="pr_url",
            field=models.URLField(blank=True, help_text="Pull request URL"),
        ),
        migrations.AddField(
            model_name="issue",
            name="test_coverage",
            field=models.IntegerField(
                blank=True, help_text="Test coverage percentage", null=True
            ),
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("author", models.CharField(max_length=255)),
                ("reviewers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="agile.issue",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "pull_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "issue", "status"],
                        name="pull_reques_organiz_34f4de_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(db_index=True, max_length=40)),
                ("message", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="agile.issue",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "code_commits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "issue", "-created_at"],
                        name="code_commit_organiz_bccd11_idx",
                    )
                ],
            },
        ),
    ]
