# Generated by Django 4.2.7 on 2026-01-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0015_alter_bookmark_note_and_more"),
        ("decisions", "0010_alter_decision_code_links_and_more"),
        ("agile", "0006_issue_branch_name_issue_ci_status_issue_ci_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionIssueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("blocks", "Blocks"),
                            ("enables", "Enables"),
                            ("relates_to", "Relates To"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_issues",
                        to="decisions.decision",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_decisions",
                        to="agile.issue",
                    ),
                ),
            ],
            options={
                "db_table": "decision_issue_links",
                "unique_together": {("decision", "issue")},
            },
        ),
        migrations.CreateModel(
            name="ConversationIssueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_issues",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_conversations",
                        to="agile.issue",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_issue_links",
                "unique_together": {("conversation", "issue")},
            },
        ),
        migrations.CreateModel(
            name="BlockerIssueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_issues",
                        to="agile.blocker",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking_blockers",
                        to="agile.issue",
                    ),
                ),
            ],
            options={
                "db_table": "blocker_issue_links",
                "unique_together": {("blocker", "issue")},
            },
        ),
    ]
