# Generated by Django 4.2.7 on 2026-01-31 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0007_decisionissuelink_conversationissuelink_and_more"),
    ]

    operations = []
