# Generated by Django 4.2.7 on 2026-01-31 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0008_burndowndata_sprintforecast_sprintvelocity_and_more"),
    ]

    operations = []
