# Generated by Django 4.2.7 on 2026-01-31 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0009_add_deployment_model"),
    ]

    operations = []
