# Generated by Django 4.2.7 on 2026-01-31 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0010_mark_existing_tables_migrated"),
    ]

    operations = []
