# Generated by Django 4.2.7 on 2026-02-01 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_searchanalytics_savedsearch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agile", "0011_add_deployment_model_final"),
    ]

    operations = [
        migrations.CreateModel(
            name="BurndownData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("remaining_points", models.IntegerField()),
                ("completed_points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "burndown_data",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("environment", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("commit_hash", models.CharField(max_length=40)),
                ("branch", models.CharField(max_length=255)),
                ("deployed_by", models.CharField(max_length=255)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "deployments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SprintForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_velocity", models.FloatField()),
                ("recommended_capacity", models.IntegerField()),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sprint_forecasts",
                "ordering": ["-sprint__start_date"],
            },
        ),
        migrations.CreateModel(
            name="SprintVelocity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_points", models.IntegerField(default=0)),
                ("completed_points", models.IntegerField(default=0)),
                ("velocity", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sprint_velocities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_hours", models.FloatField()),
                ("allocated_hours", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "team_capacities",
            },
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="projects_organiz_d764bf_idx",
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamcapacity",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="teamcapacity",
            name="sprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capacities",
                to="agile.sprint",
            ),
        ),
        migrations.AddField(
            model_name="teamcapacity",
            name="team_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sprintvelocity",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="sprintvelocity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="velocities",
                to="agile.project",
            ),
        ),
        migrations.AddField(
            model_name="sprintvelocity",
            name="sprint",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="velocity",
                to="agile.sprint",
            ),
        ),
        migrations.AddField(
            model_name="sprintforecast",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="sprintforecast",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="agile.project",
            ),
        ),
        migrations.AddField(
            model_name="sprintforecast",
            name="sprint",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecast",
                to="agile.sprint",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="burndowndata",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="burndowndata",
            name="sprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burndown_data",
                to="agile.sprint",
            ),
        ),
        migrations.AddIndex(
            model_name="teamcapacity",
            index=models.Index(
                fields=["organization", "sprint"], name="team_capaci_organiz_3a7e27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamcapacity",
            unique_together={("sprint", "team_member")},
        ),
        migrations.AddIndex(
            model_name="sprintvelocity",
            index=models.Index(
                fields=["organization", "project", "-created_at"],
                name="sprint_velo_organiz_24c9e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="burndowndata",
            index=models.Index(
                fields=["organization", "sprint", "date"],
                name="burndown_da_organiz_1545d8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="burndowndata",
            unique_together={("sprint", "date")},
        ),
    ]
