# Generated by Django 4.2.7 on 2026-02-01 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agile", "0003_decision_impact_tracking"),
        ("agile", "0012_burndowndata_deployment_sprintforecast_and_more"),
    ]

    operations = []
