# Generated by Django 4.2.7 on 2026-02-01 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_searchanalytics_savedsearch"),
        ("decisions", "0012_decisionmetric_consensussnapshot_metricdatapoint_and_more"),
        ("agile", "0013_merge_20260201_0933"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="backlog",
            name="backlog_org_project_unique",
        ),
        migrations.RemoveConstraint(
            model_name="decisionimpact",
            name="decision_impact_unique",
        ),
        migrations.RemoveConstraint(
            model_name="workflowtransition",
            name="workflow_transition_unique",
        ),
        migrations.RenameIndex(
            model_name="decisionimpact",
            new_name="decision_im_organiz_31f0f6_idx",
            old_name="decision_impact_org_decision_idx",
        ),
        migrations.RenameIndex(
            model_name="decisionimpact",
            new_name="decision_im_organiz_f0fa85_idx",
            old_name="decision_impact_org_issue_idx",
        ),
        migrations.RenameIndex(
            model_name="issuedecisionhistory",
            new_name="issue_decis_organiz_983d38_idx",
            old_name="issue_decision_history_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowtransition",
            new_name="workflow_tr_organiz_4ba3e5_idx",
            old_name="workflow_org_from_idx",
        ),
        migrations.AlterUniqueTogether(
            name="backlog",
            unique_together={("organization", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="decisionimpact",
            unique_together={("decision", "issue")},
        ),
        migrations.AlterUniqueTogether(
            name="workflowtransition",
            unique_together={
                ("organization", "from_status", "to_status", "issue_type")
            },
        ),
    ]
