# Generated by Django 6.0.2 on 2026-02-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0015_missing_jira_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unreleased', 'Unreleased'), ('released', 'Released'), ('archived', 'Archived')], default='unreleased', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='agile.project')),
            ],
            options={
                'db_table': 'releases',
                'ordering': ['-release_date'],
                'unique_together': {('project', 'version')},
            },
        ),
    ]
