# Generated by Django 6.0.2 on 2026-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0016_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
