# Generated by Django 6.0.2 on 2026-02-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0018_time_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeestimate',
            name='issue',
        ),
        migrations.RemoveIndex(
            model_name='worklog',
            name='work_logs_org_issue_idx',
        ),
        migrations.RemoveIndex(
            model_name='worklog',
            name='work_logs_user_idx',
        ),
        migrations.DeleteModel(
            name='TimeEstimate',
        ),
        migrations.DeleteModel(
            name='WorkLog',
        ),
    ]
