# Generated by Django 6.0.2 on 2026-02-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0019_remove_timeestimate_issue_and_more'),
        ('organizations', '0014_accountmanager_onpremisedeployment_slaguarantee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_pull_requests', to='organizations.organization'),
        ),
    ]
