# Generated by Django 6.0.2 on 2026-02-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0020_alter_pullrequest_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_templates', to='agile.project'),
        ),
    ]
