# Generated by Django 6.0.2 on 2026-02-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0020_recreate_time_tracking_models'),
        ('agile', '0021_alter_issuetemplate_project'),
    ]

    operations = []
