# Generated by Django 6.0.2 on 2026-02-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0022_merge_20260227_1138'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='worklog',
            new_name='work_logs_organiz_6e7468_idx',
            old_name='work_logs_org_issue_idx',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='work_logs_user_id_b11503_idx',
            old_name='work_logs_user_idx',
        ),
    ]
