# Generated by Django 6.0.2 on 2026-03-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0026_servicedeskaitriage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicedeskaitriage',
            new_name='service_des_organiz_b7eb20_idx',
            old_name='service_des_organiz_e4d47a_idx',
        ),
        migrations.RenameIndex(
            model_name='servicedeskaitriage',
            new_name='service_des_organiz_7cd6b6_idx',
            old_name='service_des_organiz_0ce01e_idx',
        ),
    ]
