# Generated by Django 4.2.7 on 2025-12-26 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("extracted_by_ai", models.BooleanField(default=False)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "action_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("update", "Update"),
                            ("decision", "Decision"),
                            ("question", "Question"),
                            ("proposal", "Proposal"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_action_items", models.JSONField(blank=True, default=list)),
                ("ai_keywords", models.JSONField(blank=True, default=list)),
                ("ai_processed", models.BooleanField(db_index=True, default=False)),
                ("ai_processing_error", models.TextField(blank=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("reply_count", models.PositiveIntegerField(default=0)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("is_pinned", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(3)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "conversation_replies",
                "ordering": ["created_at"],
            },
        ),
    ]
