# Generated by Django 4.2.7 on 2025-12-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="status_label",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("good_example", "Good Example"),
                    ("needs_followup", "Needs Follow-up"),
                    ("resolved", "Resolved"),
                    ("in_progress", "In Progress"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
