# Generated by Django 4.2.7 on 2025-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conversations",
            "0008_conversation_closed_at_conversation_closure_summary_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="context_reason",
            field=models.TextField(
                blank=True, help_text="Why are we even talking about this?"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="emotional_context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urgent", "🚨 Urgent"),
                    ("consensus", "🤝 Consensus"),
                    ("risky", "⚠️ Risky"),
                    ("experimental", "💡 Experimental"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="key_takeaway",
            field=models.CharField(
                blank=True,
                help_text="If you remember one thing, remember this",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="memory_health_score",
            field=models.IntegerField(
                default=50, help_text="0-100 score for documentation quality"
            ),
        ),
    ]
