# Generated by Django 4.2.7 on 2025-12-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0009_conversation_context_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="alternatives_considered",
            field=models.TextField(
                blank=True, help_text="What other options did we consider?"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="code_links",
            field=models.JSONField(
                blank=True, default=list, help_text="Links to PRs, commits, docs"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="plain_language_summary",
            field=models.TextField(blank=True, help_text="Non-technical explanation"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="tradeoffs",
            field=models.TextField(
                blank=True, help_text="What are the tradeoffs of this approach?"
            ),
        ),
    ]
