# Generated by Django 4.2.7 on 2025-12-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0010_conversation_alternatives_considered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="dev_action_items",
            field=models.JSONField(
                blank=True, default=list, help_text="Extracted action items"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="dev_agile_context",
            field=models.JSONField(
                blank=True, default=list, help_text="Agile classification"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="dev_future_note",
            field=models.TextField(
                blank=True, help_text="What future developers should know"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="dev_simple_summary",
            field=models.TextField(
                blank=True, help_text="Simple explanation for new developers"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="dev_technical_decision",
            field=models.JSONField(
                blank=True, default=dict, help_text="Structured decision info"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="dev_warnings",
            field=models.JSONField(
                blank=True, default=dict, help_text="Warnings and flags"
            ),
        ),
    ]
