# Generated by Django 4.2.7 on 2025-12-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
