# Generated by Django 4.2.7 on 2025-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0013_document_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="draft_saved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_draft",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
