# Generated by Django 4.2.7 on 2026-01-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0014_conversation_draft_saved_at_conversation_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="alternatives_considered",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="code_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="context_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="dev_action_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="dev_agile_context",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="dev_future_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="dev_simple_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="dev_technical_decision",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="dev_warnings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="key_takeaway",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="memory_health_score",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="plain_language_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="tradeoffs",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="why_this_matters",
            field=models.TextField(blank=True),
        ),
    ]
