# Generated by Django 4.2.7 on 2026-01-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_searchanalytics_savedsearch"),
        ("conversations", "0015_alter_bookmark_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("duplicate", "Duplicate"),
                            ("follow_up", "Follow Up"),
                            ("blocked_by", "Blocked By"),
                            ("blocks", "Blocks"),
                        ],
                        default="related",
                        max_length=50,
                    ),
                ),
                ("similarity_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child_conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_threads",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_threads",
                "ordering": ["-similarity_score"],
                "indexes": [
                    models.Index(
                        fields=["organization", "parent_conversation"],
                        name="conversatio_organiz_7fe307_idx",
                    )
                ],
                "unique_together": {("parent_conversation", "child_conversation")},
            },
        ),
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(db_index=True, max_length=255)),
                ("first_occurrence", models.DateTimeField()),
                ("last_occurrence", models.DateTimeField()),
                ("occurrence_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversations",
                    models.ManyToManyField(
                        related_name="history_records", to="conversations.conversation"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_histories",
                "ordering": ["-last_occurrence"],
                "indexes": [
                    models.Index(
                        fields=["organization", "topic"],
                        name="conversatio_organiz_f18a27_idx",
                    )
                ],
            },
        ),
    ]
