# Generated by Django 4.2.7 on 2026-08-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_conversationthread_conversationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='conversation',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='conversation',
            name='source_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'source', '-created_at'], name='conversatio_organiz_6e07a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'source', 'external_id'), name='uniq_conversation_external_ref'),
        ),
    ]
