# Generated by Django 4.2.7 on 2025-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("conversation", "Conversation"),
                            ("decision", "Decision"),
                            ("action_item", "Action Item"),
                            ("summary", "AI Summary"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("summary", models.TextField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("entities", models.JSONField(blank=True, default=list)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "vector_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("relevance_score", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "knowledge_entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("semantic", "Semantic Search"),
                            ("keyword", "Keyword Search"),
                            ("hybrid", "Hybrid Search"),
                        ],
                        default="semantic",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("clicked_result_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrendingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(db_index=True, max_length=100)),
                ("mention_count", models.PositiveIntegerField(default=0)),
                ("trend_score", models.FloatField(default=0.0)),
                ("week_mentions", models.PositiveIntegerField(default=0)),
                ("month_mentions", models.PositiveIntegerField(default=0)),
                ("related_conversations", models.PositiveIntegerField(default=0)),
                ("related_decisions", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "trending_topics",
                "ordering": ["-trend_score"],
            },
        ),
    ]
