# Generated by Django 4.2.7 on 2025-12-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingtopic",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="content_type_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="trendingtopic",
            index=models.Index(
                fields=["organization", "-trend_score"],
                name="trending_to_organiz_552086_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trendingtopic",
            unique_together={("organization", "topic")},
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="search_quer_organiz_b8ba7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "-created_at"], name="search_quer_user_id_486cee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["organization", "content_type", "-created_at"],
                name="knowledge_e_organiz_4b9c69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["organization", "-relevance_score"],
                name="knowledge_e_organiz_7909ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["vector_id"], name="knowledge_e_vector__eb50b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeentry",
            unique_together={("content_type_fk", "object_id", "organization")},
        ),
    ]
