# Generated by Django 4.2.7 on 2026-01-31 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_searchanalytics_savedsearch"),
        ("conversations", "0015_alter_bookmark_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("helpful_count", models.IntegerField(default=0)),
                ("unhelpful_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "faqs",
                "ordering": ["-helpful_count", "-view_count"],
            },
        ),
        migrations.CreateModel(
            name="FAQFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_helpful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="knowledge.faq",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "faq_feedback",
                "unique_together": {("faq", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="faq",
            index=models.Index(
                fields=["organization", "-created_at"], name="faqs_organiz_7e4a6e_idx"
            ),
        ),
    ]
