# Generated by Django 6.0.2 on 2026-02-22 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledge', '0003_faq_faqfeedback_faq_faqs_organiz_7e4a6e_idx'),
        ('organizations', '0014_accountmanager_onpremisedeployment_slaguarantee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('link_type', models.CharField(choices=[('references', 'References'), ('implements', 'Implements'), ('blocks', 'Blocks'), ('relates_to', 'Relates To'), ('supersedes', 'Supersedes'), ('derived_from', 'Derived From')], default='relates_to', max_length=20)),
                ('strength', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'content_links',
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='content_lin_source__acef25_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='content_lin_target__0c86a3_idx'), models.Index(fields=['organization', '-created_at'], name='content_lin_organiz_60f665_idx')],
                'unique_together': {('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id')},
            },
        ),
        migrations.CreateModel(
            name='ContextPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('related_conversations', models.JSONField(default=list)),
                ('related_decisions', models.JSONField(default=list)),
                ('related_tasks', models.JSONField(default=list)),
                ('related_documents', models.JSONField(default=list)),
                ('expert_users', models.JSONField(default=list)),
                ('similar_past_items', models.JSONField(default=list)),
                ('success_rate', models.FloatField(blank=True, null=True)),
                ('risk_indicators', models.JSONField(default=list)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'db_table': 'context_panels',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='context_pan_content_34a0c9_idx')],
                'unique_together': {('content_type', 'object_id', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='UnifiedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('conversation_created', 'Conversation Created'), ('decision_made', 'Decision Made'), ('task_completed', 'Task Completed'), ('meeting_scheduled', 'Meeting Scheduled'), ('document_uploaded', 'Document Uploaded'), ('comment_added', 'Comment Added'), ('status_changed', 'Status Changed')], db_index=True, max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='unified_act_organiz_508c18_idx'), models.Index(fields=['user', '-created_at'], name='unified_act_user_id_99d9a1_idx'), models.Index(fields=['content_type', 'object_id'], name='unified_act_content_64c7ac_idx')],
            },
        ),
    ]
