# Generated by Django 5.2.14 on 2026-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_agentstep'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agent_runs_organiz_ea9925_idx',
            old_name='agent_runs_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agent_runs_organiz_bb8e2f_idx',
            old_name='agent_runs_org_status_idx',
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
