# Generated by Django 4.2.7 on 2025-12-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0008_user_first_conversation_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_url", models.URLField()),
                ("channel", models.CharField(default="#general", max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("post_decisions", models.BooleanField(default=True)),
                ("post_blockers", models.BooleanField(default=True)),
                ("post_sprint_summary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "slack_integrations",
            },
        ),
        migrations.CreateModel(
            name="JiraIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("api_token", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("auto_sync_issues", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "jira_integrations",
            },
        ),
        migrations.CreateModel(
            name="GitHubIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("repo_owner", models.CharField(max_length=100)),
                ("repo_name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("auto_link_prs", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "github_integrations",
            },
        ),
    ]
