# Generated by Django 6.0.2 on 2026-02-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0012_decisionmetric_consensussnapshot_metricdatapoint_and_more'),
        ('integrations', '0002_webhook_webhookdelivery_externalintegration'),
        ('organizations', '0014_accountmanager_onpremisedeployment_slaguarantee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubintegration',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('pr_url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('branch_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('commits_count', models.IntegerField(default=0)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='decisions.decision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_pull_requests', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'pr_number')},
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('commit_url', models.URLField()),
                ('committed_at', models.DateTimeField()),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='decisions.decision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='integrations.pullrequest')),
            ],
            options={
                'ordering': ['-committed_at'],
            },
        ),
    ]
