# Generated by Django 4.2.7 on 2026-05-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_githubwebhookdelivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='githubwebhookdelivery',
            new_name='github_webh_organiz_2699d0_idx',
            old_name='github_webh_organiz_b1fb4f_idx',
        ),
        migrations.RenameIndex(
            model_name='githubwebhookdelivery',
            new_name='github_webh_integra_267019_idx',
            old_name='github_webh_integra_6b2997_idx',
        ),
        migrations.RenameIndex(
            model_name='githubwebhookdelivery',
            new_name='github_webh_integra_d15a48_idx',
            old_name='github_webh_integra_369e4f_idx',
        ),
    ]
