# Generated by Django 5.2.14 on 2026-06-12 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_rename_github_webh_organiz_b1fb4f_idx_github_webh_organiz_2699d0_idx_and_more'),
        ('organizations', '0034_rename_agent_budget_org_ym_idx_org_agent_b_organiz_f8b17f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(db_index=True, unique=True)),
                ('account_id', models.BigIntegerField(db_index=True)),
                ('account_login', models.CharField(db_index=True, max_length=128)),
                ('account_type', models.CharField(choices=[('User', 'User'), ('Organization', 'Organization')], default='Organization', max_length=16)),
                ('account_avatar_url', models.URLField(blank=True, max_length=512)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('repository_selection', models.CharField(choices=[('all', 'All repositories'), ('selected', 'Selected repositories')], default='selected', max_length=16)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_app_installations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_app_installation', to='organizations.organization')),
            ],
            options={
                'db_table': 'github_app_installations',
            },
        ),
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField(db_index=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('owner_login', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('default_branch', models.CharField(blank=True, max_length=128)),
                ('private', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('html_url', models.URLField(blank=True, max_length=512)),
                ('is_enabled_for_decisions', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='integrations.githubappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repos', to='organizations.organization')),
            ],
            options={
                'db_table': 'github_repos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='GitHubAppDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('delivery_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(default='received', max_length=24)),
                ('summary', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_app_deliveries', to='organizations.organization')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.githubappinstallation')),
                ('repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='integrations.githubrepo')),
            ],
            options={
                'db_table': 'github_app_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='githubappinstallation',
            index=models.Index(fields=['organization', 'installation_id'], name='github_app__organiz_409903_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepo',
            index=models.Index(fields=['organization', 'is_enabled_for_decisions'], name='github_repo_organiz_eafa07_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepo',
            index=models.Index(fields=['installation', 'full_name'], name='github_repo_install_ecb6a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='githubrepo',
            unique_together={('organization', 'repo_id')},
        ),
        migrations.AddIndex(
            model_name='githubappdelivery',
            index=models.Index(fields=['organization', '-created_at'], name='github_app__organiz_bc0df2_idx'),
        ),
        migrations.AddIndex(
            model_name='githubappdelivery',
            index=models.Index(fields=['installation', '-created_at'], name='github_app__install_77d9cb_idx'),
        ),
    ]
