# Generated by Django 5.2.14 on 2026-06-12 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0016_align_conversation_nullable'),
        ('integrations', '0007_githubappinstallation_githubrepo_githubappdelivery_and_more'),
        ('organizations', '0034_rename_agent_budget_org_ym_idx_org_agent_b_organiz_f8b17f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('pr_node_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('html_url', models.URLField(max_length=512)),
                ('state', models.CharField(default='open', max_length=16)),
                ('author_login', models.CharField(blank=True, max_length=128)),
                ('author_avatar_url', models.URLField(blank=True, max_length=512)),
                ('base_branch', models.CharField(blank=True, max_length=255)),
                ('head_branch', models.CharField(blank=True, max_length=255)),
                ('body_excerpt', models.CharField(blank=True, max_length=512)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('pr_updated_at', models.DateTimeField(blank=True, null=True)),
                ('link_source', models.CharField(choices=[('manual', 'Manual link from decision page'), ('badge', 'Inline knoledgr-decision marker in PR body'), ('branch', 'Branch name match'), ('action', 'knoledgr/link-decision GitHub Action')], default='manual', max_length=16)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_pull_requests', to='decisions.decision')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_pr_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_pull_requests', to='organizations.organization')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_links', to='integrations.githubrepo')),
            ],
            options={
                'db_table': 'decision_pull_requests',
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['organization', '-linked_at'], name='decision_pu_organiz_4e2e9f_idx'), models.Index(fields=['decision', '-linked_at'], name='decision_pu_decisio_851a19_idx'), models.Index(fields=['repo', 'pr_number'], name='decision_pu_repo_id_eb75ea_idx')],
                'unique_together': {('decision', 'repo', 'pr_number')},
            },
        ),
    ]
