# Generated by Django 4.2.7 on 2026-08-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_decisionpullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionpullrequest',
            name='match_runner_up_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionpullrequest',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decisionpullrequest',
            name='link_source',
            field=models.CharField(choices=[('manual', 'Manual link from decision page'), ('badge', 'Inline knoledgr-decision marker in PR body'), ('branch', 'Branch name match'), ('action', 'knoledgr/link-decision GitHub Action'), ('auto', 'Inferred automatically from PR text')], default='manual', max_length=16),
        ),
    ]
