# Generated by Django 4.2.7 on 2026-08-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0016_align_conversation_nullable'),
        ('organizations', '0034_rename_agent_budget_org_ym_idx_org_agent_b_organiz_f8b17f_idx_and_more'),
        ('integrations', '0009_decisionpullrequest_match_runner_up_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('status', models.CharField(blank=True, max_length=16)),
                ('changes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='decisions.decision')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='integrations.decisionpullrequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_files', to='organizations.organization')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_files', to='integrations.githubrepo')),
            ],
            options={
                'db_table': 'decision_files',
                'indexes': [models.Index(fields=['organization', 'repo', 'path'], name='decision_fi_organiz_16f4fb_idx'), models.Index(fields=['decision'], name='decision_fi_decisio_73e6b3_idx')],
                'unique_together': {('link', 'path')},
            },
        ),
    ]
