# Generated by Django 4.2.7 on 2026-08-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Let one GitHub installation serve more than one workspace.

    GitHub permits a single installation per account. Binding it to exactly one
    workspace therefore meant a developer with two projects under one GitHub
    login could connect only one of them: connecting the second revoked the
    first, silently, and whichever project they were not looking at stopped
    recording anything.

    Which workspace a repository feeds was always a property of the repository
    — GitHubRepo has carried its own organization from the start — so the
    OneToOneField was an artificial ceiling rather than a boundary. It becomes a
    ForeignKey recording who administers the connection.

    The repo uniqueness key moves with it. Keyed on (organization, repo_id) the
    same GitHub repository could exist once per workspace, with both rows
    receiving its webhooks and writing into different records; keyed on
    (installation, repo_id) it is single-homed and moving it means changing
    which workspace it feeds.
    """

    dependencies = [
        ('organizations', '0034_rename_agent_budget_org_ym_idx_org_agent_b_organiz_f8b17f_idx_and_more'),
        ('integrations', '0010_decisionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubappinstallation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_app_installations_owned', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='githubrepo',
            unique_together={('installation', 'repo_id')},
        ),
    ]
