# Generated by Django 4.2.7 on 2026-08-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """One repository, one project.

    GitHub is the source of the code; Knoledgr is the ground truth for what was
    decided and why. OneToOne enforces the rule that a repository cannot be the
    code for two projects, so the two line up rather than drifting.
    """

    dependencies = [
        ('agile', '0028_releases_timestamptz'),
        ('integrations', '0011_alter_githubappinstallation_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo', to='agile.project'),
        ),
    ]
