# Generated by Django 6.0.2 on 2026-02-21 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_documentcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='document_mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
