# Generated by Django 4.2.7 on 2025-12-27 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_activity"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities_organiz_d88ee6_idx",
            old_name="activities_org_created_idx",
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities_actor_i_8dd0d9_idx",
            old_name="activities_actor_created_idx",
        ),
    ]
