# Generated by Django 4.2.7 on 2025-12-28 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_user_notification_settings"),
        ("organizations", "0005_user_avatar_user_bio"),
    ]

    operations = []
