# Generated by Django 4.2.7 on 2025-12-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_merge_20251228_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="org_logos/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="primary_color",
            field=models.CharField(
                default="#000000", help_text="Hex color code", max_length=7
            ),
        ),
    ]
