# Generated by Django 4.2.7 on 2025-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_organization_logo_organization_primary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_conversation_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="first_decision_made",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="first_teammate_invited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
