# Generated by Django 6.0.2 on 2026-02-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_searchanalytics_savedsearch'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_organiz_86ff70_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_user_id_6193b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_action_bcaa71_idx',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='workflow',
        ),
        migrations.AlterUniqueTogether(
            name='workflowapproval',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='workflowapproval',
            name='workflow_instance',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeamWorkflow',
        ),
        migrations.DeleteModel(
            name='WorkflowApproval',
        ),
        migrations.DeleteModel(
            name='WorkflowInstance',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
