# Generated by Django 6.0.2 on 2026-02-20 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_plan_subscription_invoice_usagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('availability', models.TextField(blank=True, help_text='Working hours and availability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizations', models.ManyToManyField(related_name='account_manager', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnPremiseDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('deployed', 'Deployed'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='requested', max_length=20)),
                ('server_location', models.CharField(max_length=200)),
                ('server_specs', models.TextField(blank=True)),
                ('database_type', models.CharField(default='PostgreSQL', max_length=50)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('deployment_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_premise', to='organizations.organization')),
                ('technical_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_premise_deployments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SLAGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('uptime', 'Uptime'), ('response_time', 'Response Time'), ('resolution_time', 'Issue Resolution Time'), ('support_response', 'Support Response Time')], max_length=30)),
                ('guaranteed_value', models.DecimalField(decimal_places=2, help_text='e.g., 99.9 for uptime %', max_digits=5)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('met', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_guarantees', to='organizations.organization')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='SSOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('saml', 'SAML 2.0'), ('okta', 'Okta'), ('azure', 'Azure AD'), ('google', 'Google Workspace')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('entity_id', models.CharField(blank=True, max_length=500)),
                ('sso_url', models.URLField(blank=True)),
                ('x509_cert', models.TextField(blank=True)),
                ('auto_provision_users', models.BooleanField(default=True)),
                ('default_role', models.CharField(default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('training_date', models.DateTimeField()),
                ('duration_hours', models.IntegerField(default=2)),
                ('location', models.CharField(blank=True, help_text='Virtual or physical location', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('materials_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_trainings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='organizations.organization')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
