# Generated by Django 6.0.2 on 2026-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_accountmanager_onpremisedeployment_slaguarantee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meeting_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
