# Generated by Django 6.0.2 on 2026-02-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_marketplace_apps(apps, schema_editor):
    MarketplaceApp = apps.get_model('organizations', 'MarketplaceApp')
    defaults = [
        {
            'slug': 'github-advanced-sync',
            'name': 'GitHub Advanced Sync',
            'description': 'Deep PR, commit, and release sync into decisions and delivery timelines.',
            'vendor': 'Knoledgr',
            'category': 'engineering',
            'pricing': 'included',
            'docs_url': 'https://docs.knoledgr.com/integrations/github',
        },
        {
            'slug': 'jira-portfolio-bridge',
            'name': 'Jira Portfolio Bridge',
            'description': 'Cross-project rollups, dependency views, and execution drift alerts.',
            'vendor': 'Knoledgr',
            'category': 'reporting',
            'pricing': 'included',
            'docs_url': 'https://docs.knoledgr.com/integrations/jira',
        },
        {
            'slug': 'compliance-audit-exporter',
            'name': 'Compliance Audit Exporter',
            'description': 'Scheduled immutable audit exports for SOC2/ISO review cycles.',
            'vendor': 'Knoledgr',
            'category': 'security',
            'pricing': 'enterprise',
            'docs_url': 'https://docs.knoledgr.com/enterprise/compliance',
        },
        {
            'slug': 'incident-ops-feed',
            'name': 'Incident Ops Feed',
            'description': 'Stream blocker and incident signals to on-call and response channels.',
            'vendor': 'Knoledgr',
            'category': 'automation',
            'pricing': 'enterprise',
            'docs_url': 'https://docs.knoledgr.com/enterprise/incident-ops',
        },
    ]
    for payload in defaults:
        MarketplaceApp.objects.update_or_create(
            slug=payload['slug'],
            defaults=payload,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_user_goal_notifications_user_meeting_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_residency_region', models.CharField(choices=[('us', 'United States'), ('eu', 'European Union'), ('uk', 'United Kingdom'), ('ca', 'Canada'), ('apac', 'Asia Pacific')], default='us', max_length=20)),
                ('require_sso', models.BooleanField(default=False)),
                ('require_mfa', models.BooleanField(default=False)),
                ('audit_export_enabled', models.BooleanField(default=True)),
                ('third_party_app_approval_required', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('ip_allowlist', models.JSONField(blank=True, default=list)),
                ('allowed_integrations', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_policy', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(default='Knoledgr', max_length=120)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('knowledge', 'Knowledge'), ('security', 'Security'), ('automation', 'Automation'), ('reporting', 'Reporting')], default='engineering', max_length=30)),
                ('pricing', models.CharField(default='free', max_length=40)),
                ('docs_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstalledMarketplaceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('disabled', 'Disabled')], default='installed', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='organizations.marketplaceapp')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_marketplace_apps', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_marketplace_apps', to='organizations.organization')),
            ],
            options={
                'ordering': ['-installed_at'],
                'unique_together': {('organization', 'app')},
            },
        ),
        migrations.RunPython(seed_marketplace_apps, migrations.RunPython.noop),
    ]
