# Generated by Django 6.0.2 on 2026-02-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0022_merge_20260227_1138'),
        ('organizations', '0017_rolepermissionpolicy_enterpriseincident'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('incident_type', models.CharField(blank=True, help_text='Empty means all incident types', max_length=30)),
                ('min_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('escalation_delay_minutes', models.PositiveIntegerField(default=0)),
                ('create_task', models.BooleanField(default=True)),
                ('create_blocker', models.BooleanField(default=False)),
                ('notify_admins', models.BooleanField(default=True)),
                ('assign_to_role', models.CharField(default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_escalation_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['escalation_delay_minutes', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPermissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('contributor', 'Contributor')], max_length=20)),
                ('allowed_permissions', models.JSONField(blank=True, default=list)),
                ('denied_permissions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permission_scopes', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_scopes', to='agile.project')),
            ],
            options={
                'ordering': ['project__name', 'role'],
                'unique_together': {('organization', 'project', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('metric', models.CharField(choices=[('uptime', 'Uptime'), ('response_time', 'Response Time'), ('resolution_time', 'Issue Resolution Time'), ('support_response', 'Support Response Time')], max_length=30)),
                ('threshold_percent', models.DecimalField(decimal_places=2, default=99.9, max_digits=5)),
                ('lookback_days', models.PositiveIntegerField(default=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_notify_admins', models.BooleanField(default=True)),
                ('auto_create_incident', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseIncidentEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('blocker_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='organizations.enterpriseincident')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='organizations.incidentescalationrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('incident', 'rule')},
            },
        ),
    ]
