# Generated by Codex on 2026-03-03

from django.db import migrations, models


def normalize_member_roles(apps, schema_editor):
    User = apps.get_model('organizations', 'User')
    Invitation = apps.get_model('organizations', 'Invitation')
    SSOConfig = apps.get_model('organizations', 'SSOConfig')

    User.objects.filter(role='member').update(role='contributor')
    Invitation.objects.filter(role='member').update(role='contributor')
    SSOConfig.objects.filter(default_role='member').update(default_role='contributor')


def noop_reverse(apps, schema_editor):
    # Irreversible normalization to avoid reintroducing legacy role values.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_projectpermissionscope_slarule_incidentescalationrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoconfig',
            name='default_role',
            field=models.CharField(default='contributor', max_length=20),
        ),
        migrations.RunPython(normalize_member_roles, noop_reverse),
    ]
