# Generated by Django 6.0.2 on 2026-02-28

from decimal import Decimal

from django.db import migrations, models


def seed_free_plan_and_features(apps, schema_editor):
    Plan = apps.get_model('organizations', 'Plan')

    default_features = {
        'free': {
            'projects': True,
            'issues': True,
            'comments': True,
            'attachments': True,
            'basic_sprints': True,
            'advanced_analytics': False,
            'decision_twin': False,
            'decision_debt_ledger': False,
            'api_access': False,
            'priority_support': False,
            'sso_saml': False,
            'custom_integrations': False,
        },
        'starter': {
            'projects': True,
            'issues': True,
            'comments': True,
            'attachments': True,
            'basic_sprints': True,
            'advanced_analytics': False,
            'decision_twin': False,
            'decision_debt_ledger': False,
            'api_access': False,
            'priority_support': False,
            'sso_saml': False,
            'custom_integrations': False,
        },
        'professional': {
            'projects': True,
            'issues': True,
            'comments': True,
            'attachments': True,
            'basic_sprints': True,
            'advanced_analytics': True,
            'decision_twin': True,
            'decision_debt_ledger': True,
            'api_access': True,
            'priority_support': True,
            'sso_saml': False,
            'custom_integrations': False,
        },
        'enterprise': {
            'projects': True,
            'issues': True,
            'comments': True,
            'attachments': True,
            'basic_sprints': True,
            'advanced_analytics': True,
            'decision_twin': True,
            'decision_debt_ledger': True,
            'api_access': True,
            'priority_support': True,
            'sso_saml': True,
            'custom_integrations': True,
        },
    }

    Plan.objects.get_or_create(
        name='free',
        defaults={
            'price_per_user': Decimal('0.00'),
            'max_users': 3,
            'storage_gb': 1,
            'features': default_features['free'],
            'is_active': True,
        },
    )

    for plan in Plan.objects.all():
        expected = default_features.get(plan.name)
        if not expected:
            continue
        if not plan.features:
            plan.features = expected
            plan.save(update_fields=['features'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_marketplaceapp_docs_url_domain_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(
                choices=[
                    ('free', 'Free'),
                    ('starter', 'Starter'),
                    ('professional', 'Professional'),
                    ('enterprise', 'Enterprise'),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_free_plan_and_features, migrations.RunPython.noop),
    ]
