# Generated by Codex on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_free_plan_and_feature_entitlements'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='users_org_email_unique'),
        ),
    ]
