# Generated by Codex on 2026-03-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0019_normalize_member_role"),
        ("organizations", "0022_user_org_email_unique"),
    ]

    operations = []
