# Generated by Django 4.2.7 on 2026-05-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_subscription_paypal_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerinquiry',
            new_name='partner_inq_status_74c69c_idx',
            old_name='partner_inq_status_c2a297_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerinquiry',
            new_name='partner_inq_partner_11adf0_idx',
            old_name='partner_inq_partner_091cda_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='user_feedba_status_2a77ae_idx',
            old_name='userfb_status_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='user_feedba_feedbac_f0f566_idx',
            old_name='userfb_type_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='user_feedba_sentime_87e121_idx',
            old_name='userfb_sent_sub_idx',
        ),
    ]
