# Generated by Django 5.2.14 on 2026-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_webhooks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orgagentbudgetmonth',
            new_name='org_agent_b_organiz_f8b17f_idx',
            old_name='agent_budget_org_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooksubscription',
            new_name='webhook_sub_organiz_4a9e2d_idx',
            old_name='webhook_sub_org_event_idx',
        ),
        migrations.AlterField(
            model_name='orgagentbudget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orgagentbudgetmonth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
